using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Cocona.Application;
using Cocona.Command;
using Cocona.ShellCompletion.Candidate;

namespace Cocona.ShellCompletion.Generators;

public class PwshCoconaShellCompletionCodeGenerator : ICoconaShellCompletionCodeGenerator
{
    private readonly string _appName;
    private readonly string _appCommandName;
    private readonly string _appFullPath;
    private readonly ICoconaCompletionCandidates _completionCandidates;
    
    public IReadOnlyList<string> Targets { get; } = new[] {"pwsh"};
    
    public PwshCoconaShellCompletionCodeGenerator(
        ICoconaApplicationMetadataProvider applicationMetadataProvider,
        ICoconaCompletionCandidates completionCandidates
    )
    {
        _appName = Regex.Replace(applicationMetadataProvider.GetProductName(), "[^a-zA-Z0-9_]", "__");
        _appCommandName = applicationMetadataProvider.GetExecutableName();
        _appFullPath = Assembly.GetCallingAssembly().Location;
        _completionCandidates = completionCandidates;
    }
    
    public void Generate(TextWriter writer, CommandCollection commandCollection)
    {
        writer.WriteLine($"# Generated by Cocona {nameof(BashCoconaShellCompletionCodeGenerator)}");
        
        var subCommands = commandCollection.All.Where(x => !x.IsHidden && !x.IsPrimaryCommand).ToArray();
        
        WriteFunctionWrapper(writer, subCommands);
        // TODO: Add "Register-ArgumentCompleter" commands
        
        throw new NotImplementedException();
    }

    public void GenerateOnTheFlyCandidates(TextWriter writer, IReadOnlyList<CompletionCandidateValue> values)
    {
        writer.Write(string.Join(", ", values.Select(x => x.Value)));
    }

    private void WriteFunctionWrapper(TextWriter writer, IEnumerable<CommandDescriptor> subCommands)
    {
        /*
        function CoconaApp {{
            param(
                    [string]$ParamOne,
                    [string]$ParamTwo
                )
                & "/path/to/cocona-app" --param-one $ParamOne --param-two $ParamTwo
        }}
        */
        var shellParams = new StringBuilder();
        writer.WriteLine($"function {_appCommandName} {{{{");
        writer.WriteLine("    param(");
        foreach (var subCommand in subCommands)
        {
            // TODO: Support other data types (https://docs.powershelluniversal.com/automation/scripts/parameters)
            writer.WriteLine($"[string]${subCommand.Name}");
            shellParams.Append($" {subCommand.Name.ToLowerInvariant()} ${subCommand.Name}");
        }
        writer.WriteLine("    )");
        writer.WriteLine($"    & \"{_appFullPath}\"{shellParams}");
        writer.WriteLine("}}");
    }
}
